import {StyleSheet} from 'react-native';
import {Typography, Spacing, Colors, Mixins} from '_styles';

export default style = StyleSheet.create({
  nameLabel: {
    height: Mixins.scaleSize(21),
    fontFamily: Typography.FONT_ROBOTO.fontFamily,
    fontSize: Typography.FONT_SIZE_16,
    fontWeight: Typography.FONT_WEIGHT_ROBOTO,
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(21),
    letterSpacing: 0,
    color: '#424242',
  },
  itemLabel: {
    height: Mixins.scaleSize(13),
    fontFamily: Typography.FONT_ROBOTO.fontFamily,
    fontSize: Typography.FONT_SIZE_10,
    fontWeight: Typography.FONT_WEIGHT_ROBOTO,
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'left',
    color: '#505050',
  },
  deliveryIcon: {
    height: Mixins.scaleSize(19.3),
    width: Mixins.scaleSize(19.3),
  },
  deliveryLabel: {
    width: Mixins.scaleSize(41),
    height: Mixins.scaleSize(13),
    fontFamily: Typography.FONT_MONTSERRAT.fontFamily,
    fontSize: Typography.FONT_SIZE_10,
    fontWeight: Typography.FONT_WEIGHT_ROBOTO,
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(13),
    letterSpacing: 0,
    textAlign: 'left',
    color: '#1a0c3d',
  },
  deliveryView: {
    alignItems: 'center',
  },
  locationPin: {
    width: Mixins.scaleSize(10.6),
    height: Mixins.scaleSize(13.7),
  },
  kmAway: {
    height: Mixins.scaleSize(14),
    fontFamily: Typography.FONT_SEGOEUI.fontFamil,
    fontSize: Typography.FONT_SIZE_10,
    color: '#1a0c3d',
    marginLeft: Mixins.scaleSize(7.4),
    marginBottom: Mixins.scaleSize(11),
  },
  orderId: {
    width: Mixins.scaleSize(74),
    height: Mixins.scaleSize(13),
    fontFamily: Typography.FONT_ROBOTO.fontFamily,
    fontSize: Typography.FONT_SIZE_10,
    fontWeight: Typography.FONT_WEIGHT_ROBOTO,
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(13),
    letterSpacing: 0,
    textAlign: 'left',
    color: '#424242',
    marginBottom: 1,
  },
  statusLabel: {
    height: Mixins.scaleSize(21),
    fontFamily: Typography.FONT_SEGOEUI.fontFamil,
    fontSize: Typography.FONT_SIZE_16,
    fontWeight: Typography.FONT_WEIGHT_SEGOEUI,
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(21),
    letterSpacing: 0,
    textAlign: 'left',
    color: '#424242',
  },
  status: {
    height: Mixins.scaleSize(21),
    fontFamily: Typography.FONT_SEGOEUI.fontFamil,
    fontSize: Typography.FONT_SIZE_16,
    fontWeight: Typography.FONT_WEIGHT_SEGOEUI,
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(21),
    letterSpacing: 0,
    textAlign: 'left',
    color: '#41be62',
  },
  borderLine: {
    height: 0,
    borderStyle: 'solid',
    borderWidth: Mixins.scaleSize(0.5),
    borderColor: '#c7c7c7',
    marginTop: Mixins.scaleSize(8),
    marginBottom: Mixins.scaleSize(28),
  },
  fRow: {
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  fDirection: {
    flexDirection: 'row',
  },
});
