// LOGIN ACTIONS
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';

//  SPINNER ACTIONS
export const SPINNER_START = 'SPINNER_START';
export const SPINNER_STOP = 'SPINNER_STOP';

// ERROR ACTIONS
export const TOAST_SUCCESS = 'TOAST_SUCCESS';
export const TOAST_ERROR = 'TOAST_ERROR';

// REDIRECT ACTIONS
export const REDIRECT_RQUESTED = 'REDIRECT_RQUESTED';
export const REDIRECT_WITH_PARAMS_RQUESTED = 'REDIRECT_WITH_PARAMS_RQUESTED';

//GET ORDERS
export const GET_ORDERS_REQUESTED = 'GET_ORDERS_REQUESTED';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';

//GET ORDERS BY ID

export const FETCH_ORDER_BY_ID_REQUESTED = 'FETCH_ORDER_BY_ID_REQUESTED';
export const FETCH_ORDER_BY_ID_SUCCESS = 'FETCH_ORDER_BY_ID_SUCCESS';
export const FETCH_ORDER_BY_ID_FAILED = 'FETCH_ORDER_BY_ID_FAILED';
//FETCH MORE ORDERS VIA API

export const UPDATE_ORDER_REQUESTED = 'UPDATE_ORDER_REQUESTED';

// ORDERS STATUS PENDING
export const FETCH_ORDERS_STATUS_PENDING_REQUESTED =
  'FETCH_ORDERS_STATUS_PENDING_REQUESTED';
export const FETCH_ORDERS_STATUS_PENDING_SUCCESS =
  'FETCH_ORDERS_STATUS_PENDING_SUCCESS';
export const FETCH_ORDERS_STATUS_PENDING_FAILED =
  'FETCH_ORDERS_STATUS_PENDING_FAILED';
export const FETCH_MORE_ORDER_REQUESTED = 'FETCH_MORE_ORDER_REQUESTED';

// ORDERS STATUS PROCESSING
export const FETCH_ORDERS_STATUS_PROCESSING_REQUESTED =
  'FETCH_ORDERS_STATUS_PROCESSING_REQUESTED';
export const FETCH_ORDERS_STATUS_PROCESSING_SUCCESS =
  'FETCH_ORDERS_STATUS_PROCESSING_SUCCESS';
export const FETCH_ORDERS_STATUS_PROCESSING_FAILED =
  'FETCH_ORDERS_STATUS_PROCESSING_FAILED';

// UPDATE ORDER FOR KITCHEN

export const FETCH_UPDATE_ORDER_FOR_KITCHEN_REQUESTED =
  'FETCH_UPDATE_ORDER_FOR_KITCHEN_REQUSTED';
export const FETCH_UPDATE_ORDER_FOR_KITCHEN_SUCCESS =
  'FETCH_UPDATE_ORDER_FOR_KITCHEN_SUCCESS';
export const FETCH_UPDATE_ORDER_FOR_KITCHEN_FAIL =
  'FETCH_UPDATE_ORDER_FOR_KITCHEN_FAIL';

//ORDER STATUS HOLD
export const FETCH_ORDERS_STATUS_HOLD_REQUESTED =
  'FETCH_ORDERS_STATUS_HOLD_REQUESTED';
export const FETCH_ORDERS_STATUS_HOLD_SUCCESS =
  'FETCH_ORDERS_STATUS_HOLD_SUCCESS';
export const FETCH_ORDERS_STATUS_HOLD_FAILED =
  'FETCH_ORDERS_STATUS_HOLD_FAILED';

//ORDER STATUS READY
export const FETCH_ORDERS_STATUS_READY_REQUESTED =
  'FETCH_ORDERS_STATUS_READY_REQUESTED';
export const FETCH_ORDERS_STATUS_READY_SUCCESS =
  'FETCH_ORDERS_STATUS_READY_SUCCESS';
export const FETCH_ORDERS_STATUS_READY_FAILED =
  'FETCH_ORDERS_STATUS_READY_FAILED';

//FETCH USER DETAIL

export const FETCH_USER_DETAIL_REQUESTED = 'FETCH_USER_DETAIL_REQUESTED';
export const FETCH_USER_DETAIL_SUCCESS = 'FETCH_USER_DETAIL_SUCCESS';
export const FETCH_USER_DETAIL_FAILED = 'FETCH_USER_DETAIL_FAILED';

// INVENTORY

export const FETCH_MENU_ITEMS_REQUESTED = 'FETCH_MENU_ITEMS_REQUESTED';
export const FETCH_MENU_ITEMS_SUCCESS = 'FETCH_MENU_ITEMS_SUCCESS';
export const FETCH_MENU_ITEMS_FAILED = 'FETCH_MENU_ITEMS_FAILED';

//UPDATE MENU_ITEMS
export const UPDATE_MENU_ITEMS_REQUESTED = 'UPDATE_MENU_ITEMS_REQUESTE';
export const UPDATE_MENU_ITEMS_SUCCESS = 'UPDATE_MENU_ITEMS_SUCCESS';
export const UPDATE_MENU_ITEMS_FAILED = 'UPDATE_MENU_ITEMS_FAILED';

//FETCH DELIVERY BOY
export const FETCH_DELIVERY_BOY_REQUESTED = 'FETCH_DELIVERY_BOY_REQUESTED';
export const FETCH_DELIVERY_BOY_SUCCESS = 'FETCH_DELIVERY_BOY_SUCCESS';
export const FETCH_DELIVERY_BOY_FAILED = 'FETCH_DELIVERY_BOY_FAILED';

// ASSIGN DELIVERY BOY
export const ASSIGN_DELIVERY_BOY = 'ASSIGN_DELIVERY_BOY';

//ALL READY ORDER FOR DELIVERY BOY

export const FETCH_ALL_PICKUP_ORDER_FOR_DELIVERY_BOY_REQUESTED =
  'FETCH_ALL_PICKUP_ORDER_FOR_DELIVERY_BOY_REQUESTED';
export const FETCH_ALL_PICKUP_ORDER_FOR_DELIVERY_BOY_SUCCESS =
  'FETCH_ALL_PICKUP_ORDER_FOR_DELIVERY_BOY_SUCCESS';
export const FETCH_ALL_PICKUP_ORDER_FOR_DELIVERY_BOY_FAILED =
  'FETCH_ALL_PICKUP_ORDER_FOR_DELIVERY_BOY_FAILED';

// DRIVER ORDER STATUS DELIVERY
export const FETCH_DRIVER_ORDER_STATUS_DELIVERY_REQUESTED =
  'FETCH_DRIVER_ORDER_STATUS_DELIVERY_REQUESTED';
export const FETCH_DRIVER_ORDER_STATUS_DELIVERY_SUCCESS =
  'FETCH_DRIVER_ORDER_STATUS_DELIVERY_SUCCESS';
export const FETCH_DRIVER_ORDER_STATUS_DELIVERY_FAILED =
  'FETCH_DRIVER_ORDER_STATUS_DELIVERY_FAILED';

//DRIVER ORDER STATUS DELIVERED
export const FETCH_DRIVER_ORDER_STATUS_DELIVERED_REQUESTED =
  'FETCH_DRIVER_ORDER_STATUS_DELIVERED_REQUESTED';
export const FETCH_DRIVER_ORDER_STATUS_DELIVERED_SUCCESS =
  'FETCH_DRIVER_ORDER_STATUS_DELIVERED_SUCCESS';
export const FETCH_DRIVER_ORDER_STATUS_DELIVERED_FAILED =
  'FETCH_DRIVER_ORDER_STATUS_DELIVERED_FAILED';

//UPDATE DRIVER ORDER STATUS READY TO DELIVERY
export const UPDATE_DRIVER_ORDER_STATUS_READY_DELIVER_REQUESTED =
  'UPDATE_DRIVER_ORDER_STATUS_READY_DELIVER_REQUESTED';
//UPDATE DRIVER ORDER STATUS  DELIVERY TO DELIVER
export const UPDATE_DRIVER_ORDER_STATUS_DELIVER_TO_DELIVERED_REQUESTED =
  'UPDATE_DRIVER_ORDER_STATUS_DELIVER_TO_DELIVERED_REQUESTED';

//UPDATE PAYMENT STATUS
export const UPDATE_PAYMENT_STATUS_REQUESTED =
  'UPDATE_PAYMENT_STATUS_REQUESTED';

//PRINTER CONNECTED

export const PRINTER_CONNECTED_REQUEST = 'PRINTER_CONNECTED_REQUEST';
export const PRINTER_CONNECTED_SUCCESS = 'PRINTER_CONNECTED_SUCCESS';
export const PRINTER_CONNECTED_FAILED = 'PRINTER_CONNECTED_FAILED';

//ADD PRINTER

export const ADD_PRINTER_REQUEST = 'ADD_PRINTER_REQUEST';
export const ADD_PRINTER_SUCCESS = 'ADD_PRINTER_SUCCESS';
export const ADD_PRINTER_FAILED = 'ADD_PRINTER_FAILED';

// All printer list

export const ALL_PRINTERLIST_REQUEST = 'ALL_PRINTERLIST_REQUEST';
export const ALL_PRINTERLIST_SUCCESS = 'ALL_PRINTERLIST_SUCCESS';
export const ALL_PRINTERLIST_FAILED = 'ALL_PRINTERLIST_FAILED';
export const UPDATE_PRINTER_ITEM = 'UPDATE_PRINTER_ITEM';
