import {StyleSheet} from 'react-native';

export default style = StyleSheet.create({
  from: {
    height: 21,
    fontFamily: 'SegoeUI',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#e16d34',
  },
  till: {
    height: 21,
    fontFamily: 'SegoeUI',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#e16d34',
  },
  label: {
    height: 21,
    fontFamily: 'Roboto',
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
    marginBottom: 36,
  },
  numberLabel: {
    height: 21,
    fontFamily: 'SegoeUI',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#1a0c3d',
    marginBottom: 36,
  },
});
