import {StyleSheet} from 'react-native';

export default style = StyleSheet.create({
  backView: {
    flexDirection: 'row',
    paddingLeft: 15,
    height: 44,
    alignItems: 'center',
  },
  backIcon: {
    height: 15.4,
    width: 9.9,
  },
  backText: {
    marginLeft: 13,
    height: 21,
    fontFamily: 'SegoeUI',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    color: '#000000',
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: 21,
    marginRight: 31,
    marginTop: 19,
    marginBottom: 15,
  },
  nameLable: {
    fontFamily: 'SegoeUI',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#424242',
  },
  orderIdLabel: {
    fontFamily: 'SegoeUI',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#424242',
  },
  amount: {
    fontFamily: 'Roboto',
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#38bf11',
  },
  border: {
    backgroundColor: '#ffffff',
    borderStyle: 'solid',
    borderBottomWidth: 0.6,
    borderColor: '#c4c4c4',
  },
  buttonMargin: {
    marginTop: 11,
    marginLeft: 21,
    marginRight: 18,
  },
  buttonDirection: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: 28,
  },
  paymentTextLabel: {
    height: 21,
    fontFamily: 'SegoeUI',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#424242',
  },
  btn: {
    width: 92,
    height: 23,
    borderRadius: 3,
    backgroundColor: '#ff3008',
  },
  accpedBtn: {
    width: 92,
    height: 23,
    borderRadius: 3,
    backgroundColor: 'white',
    opacity: 0.5,
    borderWidth: 0.6,
    borderColor: '#ff3008',
  },
  accptedLabel: {
    fontFamily: 'Roboto',
    fontWeight: '500',
    fontStyle: 'normal',
    textAlign: 'left',
    color: '#ffffff',
    fontSize: 8,
    marginTop: 4,
    alignSelf: 'center',
  },

  accptLabel: {
    fontFamily: 'Roboto',
    fontWeight: '500',
    fontStyle: 'normal',
    textAlign: 'left',
    color: '#ffffff',
    fontSize: 8,
    marginTop: 4,
    alignSelf: 'center',
  },

  primeryButtonMargin: {
    marginBottom: 100,

    // position: 'absolute',
    // bottom: 0,
  },

  bubble: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    borderRadius: 6,
    borderColor: '#ccc',
    borderWidth: 0.5,
    padding: 15,
    width: 100,
  },
  title: {
    fontSize: 15,
    marginBottom: 5,
  },
  arrow: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderTopColor: '#fff',
    borderWidth: 16,
    alignSelf: 'center',
    marginTop: -32,
  },
  arrowBorder: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderTopColor: '#fff',
    borderWidth: 16,
    alignSelf: 'center',
    marginTop: -0.5,
  },
});
