import {StyleSheet} from 'react-native';
import {Typography, Colors, Mixins} from '_styles/index';

export default style = StyleSheet.create({
  content: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Mixins.scaleSize(10),
    alignItems: 'center',
  },
  name: {
    fontFamily: Typography.FONT_ROBOTO.fontFamily,
    fontSize: Typography.FONT_SIZE_14,
    fontWeight: '600',
    fontStyle: 'normal',
    color: Colors.BLACK,
  },
  pickupIcon: {
    height: Mixins.scaleSize(20.5),
    width: Mixins.scaleSize(22.8),
  },
  items: {
    fontFamily: Typography.FONT_ROBOTO.fontFamily,
    fontSize: Typography.FONT_SIZE_10,
    fontWeight: Typography.FONT_ROBOTO.fontWeight,
    fontStyle: 'normal',
    // lineHeight: Mixins.scaleSize(13),
    letterSpacing: 0,
    textAlign: 'left',
    color: Colors.GRAY_MEDIUM,
  },
  pickupText: {
    fontFamily: Typography.FONT_MONTSERRAT.fontFamily,
    fontSize: Typography.FONT_SIZE_10,
    fontWeight: Typography.FONT_ROBOTO.fontWeight,
    fontStyle: 'normal',
    lineHeight: 19,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#1a0c3d',
  },
  timeR: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  delivery: {
    fontFamily: Typography.FONT_MONTSERRAT.fontFamily,
    fontSize: Typography.FONT_SIZE_10,
    fontWeight: Typography.FONT_ROBOTO.fontWeight,
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(13),
    letterSpacing: 0,
    textAlign: 'left',
    color: '#1a0c3d',
  },
  deliveryIcon: {
    height: Mixins.scaleSize(23.5),
    width: Mixins.scaleSize(24.1),
  },
  timeIcon: {
    height: Mixins.scaleSize(14.7),
    width: Mixins.scaleSize(14.6),
  },
  time: {
    fontFamily: Typography.FONT_SEGOEUI.fontFamily,
    fontSize: Typography.FONT_SIZE_12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textAlign: 'left',
    color: '#1a0c3d',
    alignItems: 'center',
  },
  kmAway: {
    fontFamily: Typography.FONT_SEGOEUI.fontFamily,
    fontSize: Typography.FONT_SIZE_12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textAlign: 'left',
    color: '#1a0c3d',
  },
  orderId: {
    fontFamily: Typography.FONT_ROBOTO.fontFamily,
    fontSize: Typography.FONT_SIZE_16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(21),
    letterSpacing: 0,
    textAlign: 'left',
    color: Colors.BLACK,
  },
  borderBottom: {
    margin: Mixins.scaleSize(15),
  },
  orderPrice: {
    width: Mixins.scaleSize(27),
    height: Mixins.scaleSize(21),
    fontFamily: Typography.FONT_SEGOEUI.fontFamily,
    fontSize: Typography.FONT_SIZE_16,
    fontWeight: Typography.FONT_SEGOEUI.fontWeight,
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(21),
    letterSpacing: 0,
    textAlign: 'left',
    color: Colors.ACTIVATE,
  },
  rsSymbol: {
    color: Colors.ACTIVATE,
  },

  orderIdRs: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Mixins.scaleSize(10),
  },
  timeRemaining: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Mixins.scaleSize(8),
    borderStyle: 'solid',
    borderBottomWidth: Mixins.scaleSize(0.5),
    borderColor: Colors.GRAY_LIGHT,
  },
  timeRemainingText: {
    height: Mixins.scaleSize(21),
    fontFamily: 'Roboto',
    fontSize: Typography.FONT_SIZE_16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(21),
    letterSpacing: 0,
    textAlign: 'left',
    color: '#565656',
  },
  RemainingTimer: {
    height: Mixins.scaleSize(21),
    fontFamily: 'SegoeUI',
    fontSize: Typography.FONT_SIZE_16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(21),
    letterSpacing: 0,
    textAlign: 'left',
    color: '#e16d34',
  },
  border: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Mixins.scaleSize(10),
    borderStyle: 'solid',
    borderBottomWidth: Mixins.scaleSize(0.5),
    borderColor: Colors.GRAY_LIGHT,
  },
  distanceView: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
});
