import {StyleSheet} from 'react-native';
import {Typography, Spacing, Colors, Mixins} from '_styles';

export default style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.WHITE,
  },
  img: {
    width: Mixins.scaleSize(374.8),
    height: Mixins.scaleSize(298),
  },
  noPickLabel: {
    height: Mixins.scaleSize(21),
    fontFamily: Typography.FONT_FAMILY_SEGOEUI,
    fontSize: Typography.FONT_SIZE_16,
    fontWeight: Typography.FONT_WEIGHT_SEGOEUI,
    fontStyle: 'normal',
    lineHeight: Mixins.scaleSize(21),
    letterSpacing: 0,
    textAlign: 'left',
    color: '#1a0c3d',
  },
  main: {
    marginTop: 27.4,
    marginHorizontal: 29,
    flexWrap: 'wrap',
  },
  fDirection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  map: {
    height: 72,
    width: 75,
    marginRight: 13,
  },
  nameLabel: {
    height: 19,
    fontFamily: 'Montserrat',
    fontSize: 16,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 19,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#1a0c3d',
  },
  icon: {
    width: 9.9,
    height: 13.7,
    marginRight: 6,
  },
  deliveryLabel: {
    fontFamily: 'SegoeUI',
    fontSize: 14,
    fontWeight: '600',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: '#000000',
    // alignSelf: 'center',
  },
  addressLabel: {
    fontFamily: 'SegoeUI',
    fontSize: 10,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 14,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#616161',
    // alignSelf: 'center',
  },
  btnView: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  marginR: {
    marginRight: 22,
  },
  activeBtn: {
    width: 92,
    height: 23,
    borderRadius: 3,
    backgroundColor: '#ff3008',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#ff3008',
  },
  inActiveBtn: {
    width: 92,
    height: 23,
    borderRadius: 3,
    backgroundColor: '#ffffff',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#ff3008',
  },
  inActiveBtnText: {
    flex: 1,
    fontFamily: 'Roboto',
    fontSize: 8,
    marginTop: 4,
    fontWeight: '500',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '#ff3008',
    alignSelf: 'center',
    justifyContent: 'space-between',
    textAlign: 'center',
  },
  activeBtnText: {
    flex: 1,
    fontFamily: 'Roboto',
    fontSize: 8,
    marginTop: 4,
    fontWeight: '500',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '#ffffff',
    alignSelf: 'center',
    justifyContent: 'space-between',
    textAlign: 'center',
    backgroundColor: '#ff3008',
  },
  border: {
    borderStyle: 'solid',
    borderWidth: 0.7,
    borderColor: '#c7c7c7',
    marginTop: 10,
    // flexDirection: 'column',
  },
});
